system:
  port: 8080

# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[github.com/zhaoxiaoyang741/gin-admin/server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1

db:
  host: 192.168.217.129
  port: 5432
  hostname: root
  password: pg123456
  database: gin-admin
  # 最大连接数
  maxopenconns: 25
  # 最大空闲连接
  maxidleconns: 5
  # 连接超时（秒）
  connmaxlifetime: 5
  logstatus: false
  loglevel: info
