system:
  port: 8080

# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[github.com/zhaoxiaoyang741/gin-admin/server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1
